name: PDFium Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List Windows SDKs
        run: dir "C:\Program Files (x86)\Windows Kits\10\Include"
        shell: powershell
        
      - name: Generate Projects
        run: pdfium.gen.projects.bat
        shell: cmd

      - name: Build Debug ARM64
        run: pdfium.build.debug.arm64.bat
        shell: cmd

      - name: Build Debug x64
        run: pdfium.build.debug.x64.bat
        shell: cmd

      - name: Build Debug x86
        run: pdfium.build.debug.x86.bat
        shell: cmd

      - name: Build Release ARM64
        run: pdfium.build.release.arm64.bat
        shell: cmd

      - name: Build Release x64
        run: pdfium.build.release.x64.bat
        shell: cmd

      - name: Build Release x86
        run: pdfium.build.release.x86.bat
        shell: cmd

      - name: Collect All Artifacts
        run: |
          mkdir package
          mkdir package\include
          mkdir package\Debug\arm64
          mkdir package\Debug\x64
          mkdir package\Debug\x86
          mkdir package\Release\arm64
          mkdir package\Release\x64
          mkdir package\Release\x86

          copy pdfium\out\Debug_GN_arm64\pdfium.dll package\Debug\arm64\
          copy pdfium\out\Debug_GN_arm64\pdfium.dll.lib package\Debug\arm64\
          copy pdfium\out\Debug_GN_arm64\pdfium.dll.pdb package\Debug\arm64\

          copy pdfium\out\Debug_GN_x64\pdfium.dll package\Debug\x64\
          copy pdfium\out\Debug_GN_x64\pdfium.dll.lib package\Debug\x64\
          copy pdfium\out\Debug_GN_x64\pdfium.dll.pdb package\Debug\x64\

          copy pdfium\out\Debug_GN_x86\pdfium.dll package\Debug\x86\
          copy pdfium\out\Debug_GN_x86\pdfium.dll.lib package\Debug\x86\
          copy pdfium\out\Debug_GN_x86\pdfium.dll.pdb package\Debug\x86\

          copy pdfium\out\Release_GN_arm64\pdfium.dll package\Release\arm64\
          copy pdfium\out\Release_GN_arm64\pdfium.dll.lib package\Release\arm64\
          copy pdfium\out\Release_GN_arm64\pdfium.dll.pdb package\Release\arm64\

          copy pdfium\out\Release_GN_x64\pdfium.dll package\Release\x64\
          copy pdfium\out\Release_GN_x64\pdfium.dll.lib package\Release\x64\
          copy pdfium\out\Release_GN_x64\pdfium.dll.pdb package\Release\x64\

          copy pdfium\out\Release_GN_x86\pdfium.dll package\Release\x86\
          copy pdfium\out\Release_GN_x86\pdfium.dll.lib package\Release\x86\
          copy pdfium\out\Release_GN_x86\pdfium.dll.pdb package\Release\x86\

      - name: Copy public headers to package\include
        run: |
          xcopy /S /Y pdfium\public\*.h package\include

      - name: Package all artifacts
        run: powershell Compress-Archive -Path package\* -DestinationPath pdfium_build.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfium_build
          path: pdfium_build.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: daily-build-${{ github.run_id }}
          release_name: Daily Build ${{ github.run_id }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pdfium_build.zip
          asset_name: pdfium_build.zip
          asset_content_type: application/zip